name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy --all-features --release --verbose
    - name: Build
      run: cargo build --all-features --release --verbose
    - name: Run tests
      run: cargo test --all-features --release --verbose
    - name: Build documentation
      run: cargo doc --all-features --release --verbose
    - name: Save files
      uses: actions/upload-artifact@v4
      with:
        name: factordb-rust
        path: |
          target/release/factordb
          target/doc
