name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: cargo clippy --all-features --release --verbose
    - name: Build
      run: cargo build --all-features --release --verbose
    - name: Run tests
      run: cargo test --all-features --release --verbose
    - name: Build documentation
      # temporary workaround due to issues with upload-artifact on windows
      # https://github.com/actions/upload-artifact/issues/485
      if: ${{ matrix.os != 'windows-latest' }}
      run: cargo doc --all-features --release --verbose
    - name: Save files
      uses: actions/upload-artifact@v4
      with:
        name: factordb-${{ matrix.target }}
        path: |
          target/release/factordb
          target/release/factordb.exe
          target/doc
